#!/bin/bash
#
# *********************************************************************
# This script can be used to execute a stop action a specified amount
# of seconds before the end of the walltime is reached
# Based on the PBS_WALLTIME it will execute a user specified action
# after PBS_WALLTIME - GRACETIME seconds
# The user specified action should be added at the end of this script
#
# Recent versions of this script can be obtained from
# /export/disk1/home1/avanzuijlen/scripts
#
# Questions/remarks can be sent to A.H.vanZuijlen@tudelft.nl
# 29-04-2017
# *********************************************************************

if [ "X$1" = "X" ]
    then
    echo "Usage: StopAction gracetime"
    echo " gracetime : time [s] before end of walltime to execute a stop action"
    echo " "
    echo "This script will execute a stop action specified by the user in this script to"
    echo "stop the submitted job. The script will execute the stop action after"
    echo "PBS_WALLTIME - GRACETIME seconds. If PBS_WALLTIME does not exist, the stop"
    echo "action is executed after GRACETIME seconds. This can be used to test the stop"
    echo "action"
    exit
else
    GRACETIME=$1
fi

# Check whether running in the PBS environment
if [ "X$PBS_WALLTIME" = "X" ]
    then
    WAITTIME=$GRACETIME
else
    let WAITTIME=$PBS_WALLTIME-$GRACETIME
    if [ $WAITTIME -lt 0 ]
        then
        echo "WARNING: GRACETIME ($GRACETIME) larger than PBS_WALLTIME ($PBS_WALLTIME)"
        echo "WARNING: setting WAITTIME to 0"
        WAITTIME=0
    fi
fi

echo "StopAction: Hibernating $WAITTIME seconds ..."
sleep $WAITTIME
echo "StopAction: Executing stop action ..."

###################################################################################
# Prescribe the stop action below this line
###################################################################################

# Change stopAt to writeNow in controlDict when 20 min left in walltime
# \s means any number of tabs or spaces
# .* means find pattern whatever is before .* and don't care what's after
sed -i 's/stopAt\s.*/stopAt    writeNow;/' ./system/controlDict

touch stopfile.stop
